# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b99b1080b62b9932a154babfcd5e00f9931f42c3183e22e06e7633fd78365ce19f1b37f077d7872d5b3095c15967a8c44dba5162b496319eecc2999e5167b3a

test:
  secret_key_base: b8453697d0fee6c05bcc33078822deea7e457af917b32b039263181c239d9f6d53b2e6695514ba38c49992d7215298d7385e1e82cea011eda5ad47357383ed36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
